# Generated by Django 4.1.2 on 2022-10-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.genders'),
        ),
    ]
